### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Coding-Enthusiast** [Coding-Enthusiast/FinderOuter#47]
This is a short roadmap to loosely outline the plans for the future releases. This issue will be updated with time.  
Each release usually takes a month or two but can take more time depending on complexity and developer's free time.

### v 0.14.0
- [ ] Code cleanup (remove unused code, simplify comparers, remove old ECC code, ...)
- [ ] Code improvement (main focus will be on VMs and basic Services)
- [ ] Some UI improvements 
- [ ] Add missing parts to knowledge-base and add more help buttons to UI
- [ ] Some tests

### v 0.15.0
- [ ] New option for user to limit the search to a smaller group of variables; this could be characters in a WIF, words in a mnemonic or characters in a password
- [ ] New option for user to recover passwords (for both BIP38 and BIP39) that are made of words

### v 1.0.0
- [ ] Maximum test coverage
- [ ] Maximum bug fixes

### v 1.1.0
- [ ] Use SIMD wherever possible (mostly all hash algorithms and some of the recovery services)

### v 1.2.0
- [ ] Try to add pause/resume capability

### v 1.3.0
- [ ] (possibly) add wallet file password recovery. The problem is lack of clear documentation and example file.

### v 2.0.0
- [ ] GPU support

**Comment by Andromalius77** [comment]
Thank you for the wonderful program. 

Is it possible to add my own list of words for restoring the Electrum wallet seed phrase? The seed phrase is from 2010, and some words are not included in the 2048 and 1624 lists. I found an old list of words, but it is long.

**Comment by Coding-Enthusiast** [comment]
> Thank you for the wonderful program.
> 
> Is it possible to add my own list of words for restoring the Electrum wallet seed phrase? The seed phrase is from 2010, and some words are not included in the 2048 and 1624 lists. I found an old list of words, but it is long.

No, because the implemented algorithm here requires a fixed length.
